---
- name: Install docker
  hosts: k8s_masters
  remote_user: root
  gather_facts: false
  vars:
    local_docker_config_path: ../docker/daemon.json

  tasks:
    - name: Add docker offical repo
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgcakey: https://download.docker.com/linux/centos/gpg
        exclude:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        file: docker-ce
        state: present

    - name: Add rpm key
      ansible.builtin.rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker-ce-19.03.11
          - docker-ce-cli-19.03.11
          - containerd.io-1.2.13
        disable_excludes: docker-ce-stable
        state: present

    - name: Create /etc/docker if it does not exist
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: Configure docker daemon
      ansible.builtin.copy:
        src: "{{ local_docker_config_path }}"
        dest: /etc/docker/daemon.json
        mode: "0644"

    - name: Start and enabled auto-start docker daemon
      ansible.builtin.systemd:
        name: docker.service
        daemon_reload: true
        enabled: true
        state: started
